<template>
  <table border="1" cellspacing="0" cellpadding="0" style="width: 100%">
    <thead>
      <tr>
        <th></th>
        <th>启动会评审</th>
        <th>方案设计评审</th>
        <th>系统上线评审</th>
        <th>阶段验收评审</th>
        <th>项目验收评审</th>
        <th>项目后评价评审</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>智数部负责人</td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
      </tr>
      <tr>
        <td>智数部分管领导</td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
      </tr>
      <tr>
        <td>业务部门</td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
      </tr>
      <tr>
        <td>数据</td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td></td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
      </tr>
      <tr>
        <td>技术</td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td></td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
      </tr>
      <tr>
        <td>安全</td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td></td>
        <td></td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
      </tr>
      <tr>
        <td>PMO</td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td></td>
        <td></td>
        <td></td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
      </tr>
      <tr>
        <td>项目总监</td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
        <td>
          <van-image
            class="icon-done-img"
            width="11"
            height="12"
            fit="cover"
            :src="data.doneImg"
          />
        </td>
      </tr>
    </tbody>
  </table>
</template>

<script setup>
import { reactive } from "vue";

const data = reactive({
  doneImg: require("@/assets/images/icon-done.png"),
});
</script>

<style lang="less" scoped>
table {
  border-collapse: collapse;
  border-color: #dee0e3;
  width: 100%;
  overflow: auto;
  box-sizing: border-box;
  thead {
    th {
      background-color: #e1eafe;
      font-size: 14px;
      color: #1f2329;
      text-align: center;
      font-weight: normal;
      min-width: 100px;
      border: 1px solid #dee0e3 !important;
      border-color: #dee0e3 !important;
    }
  }
  tbody {
    tr {
      td {
        font-size: 14px;
        color: #1f2329;
        text-align: center;
        border: 1px solid #dee0e3 !important;
        border-color: #dee0e3 !important;
      }
    }
  }
  .icon-done-img {
    transform: translateY(2px);
  }
}
</style>
